package view;

import java.awt.EventQueue;
import javax.swing.JOptionPane;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

import DAO.NhanVienDAO;
import DAO.SanPhamDAO;
import model.NhanVien;
import model.SanPham;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

public class QuanLySanPham extends javax.swing.JFrame {

    /**
     * Creates new form QuanLySanPham
     */
	DefaultTableModel spTable1;
    public QuanLySanPham() {
        initComponents();
        this.setLocationRelativeTo(null);
        spTable1=new DefaultTableModel() {
        	@Override
        	public boolean isCellEditable(int row, int column) {
        		// TODO Auto-generated method stub
        		return false;
        	};
        };
        spTable.setModel(spTable1);
        spTable1.addColumn("MaSanPham");
        spTable1.addColumn("TenSanPham");
        spTable1.addColumn("Loai");
        
        spTable1.addColumn("Size");
        spTable1.addColumn("Gia");
        ArrayList<SanPham>list= SanPhamDAO.getInstance().selectAll();
        for (SanPham sp:list) {
        	spTable1.addRow(new Object[] {sp.getMaSP(),sp.getTenSp(),sp.getLoai(),sp.getSize(),sp.getGia()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		 int selectionIndex = spTable.getSelectedRow();
               if (selectionIndex != -1) { 
                   String MaNV = (String) spTable.getValueAt(selectionIndex, 0);
                   SanPham nv1 = SanPhamDAO.getInstance().selectById(MaNV);

                   
                   txtMSP.setText(nv1.getMaSP());
                   txtTSP.setText(nv1.getTenSp());
                   
                   jComboBox1.setSelectedItem(nv1.getLoai());
                  
                   txtSL.setText(nv1.getSize() );
                   txtGia.setText(nv1.getGia() + "");
                   
           }
      	}
        	
        });
        spTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMSP = new javax.swing.JTextField();
        txtTSP = new javax.swing.JTextField();
        txtSL = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		SanPham sp =new SanPham();
        		String masp=txtMSP.getText();
        		String tensp=txtTSP.getText();
        		String Size=txtSL.getText();
        		String Loai=jComboBox1.getSelectedItem().toString();
        		sp.setMaSP(masp);
            	sp.setTenSp(tensp);
            	sp.setSize(Size);
            	sp.setLoai(Loai);
            	
    			
            	
            	
            	
            	
            	
            	
            	try {
            		
            		sp.setGia(Integer.parseInt(txtGia.getText()));
            		
            	}catch(Exception e1){
            		
            		JOptionPane.showMessageDialog(QuanLySanPham.this ,"Bạn Phải Nhập 1 kiểu só nguyên vào Giá ");
            		
            	}
            	if(masp==null||masp.isEmpty()||tensp==null||tensp.isEmpty()||Size==null||Size.isEmpty()||Loai==null||Loai.isEmpty()) {
            		JOptionPane.showMessageDialog(QuanLySanPham.this ,"Bạn chưa điền đủ thông tin ");
            		return ;
            		
            	}
            	 if (checkMasp(masp)==1) {
            		JOptionPane.showMessageDialog(QuanLySanPham.this ,"Mã sản phẩm bạn nhập đã bị trùng ");
            		return ;
            		
            	}
            	else {
            		SanPhamDAO.getInstance().insert(sp);
            		JOptionPane.showMessageDialog(QuanLySanPham.this, "Thêm thành công");
            		
            	}
            	
            	spTable1.setRowCount(0);
        		  ArrayList<SanPham>list= SanPhamDAO.getInstance().selectAll();
        	        for (SanPham sp1:list) {
        	        	spTable1.addRow(new Object[] {sp1.getMaSP(),sp1.getTenSp(),sp1.getLoai(),sp1.getSize(),sp1.getGia()});
        	        }
            	
        	
        	}
        });
        jButton2 = new javax.swing.JButton();
        jButton2.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
//        		 int selectionIndex = spTable.getSelectedRow();
////                 if (selectionIndex != -1) { 
//                     String MaNV = (String) spTable.getValueAt(selectionIndex, 0);
//                     SanPham nv1 = SanPhamDAO.getInstance().selectById(MaNV);
//
//                     
//                     txtMSP.setText(nv1.getMaSP());
//                     txtTSP.setText(nv1.getTenSp());
//                     
//                     jComboBox1.setSelectedItem(nv1.getLoai());
//                    
//                     txtSL.setText(nv1.getSoLuong() + "");
//                     txtGia.setText(nv1.getGia() + "");
                     
//             }
        	}
        });
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int selecIndex=spTable.getSelectedRow();
        		if(selecIndex==-1) {
        			JOptionPane.showMessageDialog(QuanLySanPham.this,"Vui Lòng chọn sản phâm bạn muốn sửa");

        		}
        		else {
        			
        				String Masp=(String)spTable.getValueAt(selecIndex, 0);
        				
        				SanPhamDAO.getInstance().delete(Masp);
        				boolean isTrue=true;
                    	SanPham sp1=new SanPham();
                    	try {
                    		
                    		
                    		sp1.setMaSP(txtMSP.getText());
                    		sp1.setTenSp(txtTSP.getText());
                    		
                        
                        	sp1.setLoai(jComboBox1.getSelectedItem().toString());
                        	sp1.setSize(txtSL.getText());
                    		sp1.setGia(Integer.parseInt(txtGia.getText()));
                    		
                    	}catch(Exception e1){
                    		JOptionPane.showMessageDialog(QuanLySanPham.this, "Bạn phải nhập số:");
                    		isTrue=false;
                    	}
                    	
                    	if(isTrue) {
                    		SanPhamDAO.getInstance().insert(sp1);
                    		JOptionPane.showMessageDialog(QuanLySanPham.this, "Sửa thành công:");
                    		
                    	
                    		
                    	}
                    	spTable1.setRowCount(0);
              		  ArrayList<SanPham>list= SanPhamDAO.getInstance().selectAll();
              	        for (SanPham sp2:list) {
              	        	spTable1.addRow(new Object[] {sp2.getMaSP(),sp2.getTenSp(),sp2.getLoai(),sp2.getSize(),sp2.getGia()});
              	        }
            			
        				
        			}
        		
        		
            	
            	
            	
          	
        	}
        });
        jButton3 = new javax.swing.JButton();
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int deleteIndex=spTable.getSelectedRow();
        		if(deleteIndex==-1) {
        			JOptionPane.showMessageDialog(QuanLySanPham.this,"vui lòng chọn Sản Phẩm trước ","Lỗi",JOptionPane.ERROR_MESSAGE);
        			
        		}
        		else {
        			int confirm = JOptionPane.showConfirmDialog(QuanLySanPham.this, "Ban có chắc chắc muốn xóa  ?");
        			if(confirm==JOptionPane.YES_OPTION) {
        				String MaNV=(String)spTable.getValueAt(deleteIndex, 0);
        				SanPhamDAO.getInstance().delete(MaNV);
        				
        			}
        			spTable1.setRowCount(0);
            		  ArrayList<SanPham>list= SanPhamDAO.getInstance().selectAll();
            	        for (SanPham sp2:list) {
            	        	spTable1.addRow(new Object[] {sp2.getMaSP(),sp2.getTenSp(),sp2.getLoai(),sp2.getSize(),sp2.getGia()});
            	        }
        		}
        	}
        });
        jButton5 = new javax.swing.JButton();
        jButton5.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String tensp = JOptionPane.showInputDialog(null,"Mời bạn Nhập Tên Sản Phẩm :");
//        		String name =txtTSP.getText();
        		if(tensp.length()>0) {
        			ArrayList<SanPham> list=SanPhamDAO.getInstance().findByName(tensp);
        			spTable1.setRowCount(0);
          		 
          	        for (SanPham sp2:list) {
          	        	spTable1.addRow(new Object[] {sp2.getMaSP(),sp2.getTenSp(),sp2.getLoai(),sp2.getSize(),sp2.getGia()});
          	        }
        	}
        	}
        });
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Quản Lý Sản Phẩm");

        spTable.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"MaSP","TenSP","Loai","Size","Gia"
        	}
        ));
        jScrollPane1.setViewportView(spTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Mã Sản Phẩm :");

        jLabel4.setText("Tên Sản Phẩm:");

        jLabel5.setText("Loại:");

        jLabel6.setText("Size");

        jLabel7.setText("Giá:");

        txtTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm");

        jButton2.setText("Sửa");

        jButton3.setText("Xóa");

        jButton5.setText("Tìm Kiếm");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trà Sữa", "Cafe", "Trà ", "Khác" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMSP)
                                .addComponent(txtTSP)
                                .addComponent(txtSL)
                                .addComponent(txtGia, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(46, 46, 46)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(40, 40, 40)
                .addComponent(jButton5)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        
        btnHome = new JButton();
        btnHome.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		Home home=new Home();
        		home.setVisible(true);
        	}
        });
        btnHome.setText("Home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btnHome, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        					.addGap(231)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE)
        					.addGap(0, 304, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(21)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel1)
        				.addComponent(btnHome, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 427, GroupLayout.PREFERRED_SIZE)
        					.addGap(0, 72, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable spTable;
    private javax.swing.JTextField txtMSP;
    private javax.swing.JTextField txtTSP;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtGia;
    private JButton btnHome;
    // End of variables declaration     
    private int checkMasp(String masp) {
    	for (int i=0;i<spTable.getRowCount();i++)
    	{
    		if(masp.equals(spTable.getValueAt(i, 0))) {
    			return 1;
    		}
    		
    	}
    	return 0;
    }
}
