package view;

import java.awt.EventQueue;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

import DAO.NhanVienDAO;
import model.NhanVien;
import view.QuanLyNhanVien;

import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.GroupLayout;

public class QuanLyNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNhanVien
     */
	 DefaultTableModel defaultTable;
	NhanVien nV=new NhanVien();
	NhanVienDAO nv=new NhanVienDAO();
    public QuanLyNhanVien() {
        initComponents();
        this.setLocationRelativeTo(null);
        defaultTable=new DefaultTableModel() {
         	@Override
         	public boolean isCellEditable(int row, int column) {
         		// TODO Auto-generated method stub
         		return false;
         	};
         };
         nvTable.setModel(defaultTable);
         defaultTable.addColumn("MaNV");
         defaultTable.addColumn("Ten");
         defaultTable.addColumn("ChucVu");
         
         defaultTable.addColumn("NgaySinh");
         defaultTable.addColumn("GioiTinh");
         defaultTable.addColumn("SDT");
         defaultTable.addColumn("Email");
         defaultTable.addColumn("Luong");
         defaultTable.addColumn("DiaChi");
         ArrayList<NhanVien>list= NhanVienDAO.getInstance().selectAll();
         for (NhanVien nv:list) {
         	defaultTable.addRow(new Object[] {nv.getMaNV(),nv.getTen(),nv.getChucVu(),nv.getNgaySinh(),nv.getGioiTinh(),nv.getSDT(),
         			nv.getEmail(),nv.getLuong(),nv.getDiaChi()});
         }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMNV = new javax.swing.JTextField();
        txtTNV = new javax.swing.JTextField();
        txtNS = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSĐTNV = new javax.swing.JTextField();
        txtEmailNV = new javax.swing.JTextField();
        txtLuongNV = new javax.swing.JTextField();
        NamButton1 = new javax.swing.JRadioButton();
        NuButton1 = new javax.swing.JRadioButton();
        ChucVuBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int selecIndex=nvTable.getSelectedRow();
        		NhanVien nV=new NhanVien();
        		if(selecIndex==-1) {
        			JOptionPane.showMessageDialog(QuanLyNhanVien.this,"Vui Lòng chọn nhân viên muốn sửa");
        			
        		}
        		else {
        			
        				String MaNV=(String)nvTable.getValueAt(selecIndex, 0);
        				nv.getInstance().delete(MaNV);
        				String manv=txtMNV.getText();
        		    	String Ten=txtTNV.getText();
        		    	String sdt=txtSĐTNV.getText();
        		    	String email=txtEmailNV.getText();
        		    	String diachi=txtDiaChi.getText();
        		    	String ngaysinh=txtNS.getText();
        		    	
        		    	nV.setMaNV(manv);
        		    	nV.setTen(Ten);
        		    	nV.setSDT(sdt);
        		    	nV.setChucVu(ChucVuBox1.getSelectedItem().toString());
        		    	nV.setEmail(email);
        		    	nV.setDiaChi(diachi);
        		    	nV.setNgaySinh(ngaysinh);
                    	
                    	String GioiTinh="";
                    	if(NamButton1.isSelected())
                    	{
                    		GioiTinh="Nam";
                    	}
                    	else  {
                    		GioiTinh="Nu";
                    		
                    	}
                    	
                    	
                    	nV.setGioiTinh(GioiTinh);
                    	try {
                    		nV.setLuong(Integer.parseInt(txtLuongNV.getText()));
                    		
                    	}catch(Exception e1){
                    		JOptionPane.showMessageDialog(QuanLyNhanVien.this, "Bạn phải nhập số:");
                    		
                    	}
                    	if(manv==null||manv.isEmpty()||Ten==null||Ten.isEmpty()||sdt==null||sdt.isEmpty()||email==null||email.isEmpty()||diachi==null||diachi.isEmpty()||ngaysinh==null||ngaysinh.isEmpty()) {
                    		JOptionPane.showMessageDialog(QuanLyNhanVien.this ,"Bạn chưa điền đủ thông tin ");
                    		
                    	}
                    	
                    	
                    	else {
                    		nv.getInstance().insert(nV);
                    		JOptionPane.showMessageDialog(QuanLyNhanVien.this, "Sửa thành công:");
                    		
                    	
                    		
                    	}
                    	
                    	defaultTable.setRowCount(0);
                		  ArrayList<NhanVien>list= NhanVienDAO.getInstance().selectAll();
                	        for (NhanVien nv:list) {
                	        	defaultTable.addRow(new Object[] {nv.getMaNV(),nv.getTen(),nv.getChucVu(),nv.getNgaySinh(),nv.getGioiTinh(),nv.getSDT(),
                	        			nv.getEmail(),nv.getLuong(),nv.getDiaChi()});
                	        }
                		
                		
                	
        				
        			}
        	}	
        		
        });
        jButton3 = new javax.swing.JButton();
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int deleteIndex=nvTable.getSelectedRow();
        		if(deleteIndex==-1) {
        			JOptionPane.showMessageDialog(QuanLyNhanVien.this,"Vui lòng chọn nhân viên trước","Lỗi",JOptionPane.ERROR_MESSAGE);
        			
        		}
        		else {
        			int confirm = JOptionPane.showConfirmDialog(QuanLyNhanVien.this, "Ban có chắc chắc muốn xóa không ?");
        			if(confirm==JOptionPane.YES_OPTION) {
        				String MaNV=(String)nvTable.getValueAt(deleteIndex, 0);
        				nv.getInstance().delete(MaNV);
        				
        			}
        		}
        		defaultTable.setRowCount(0);
      		  ArrayList<NhanVien>list= NhanVienDAO.getInstance().selectAll();
      	        for (NhanVien nv:list) {
      	        	defaultTable.addRow(new Object[] {nv.getMaNV(),nv.getTen(),nv.getChucVu(),nv.getNgaySinh(),nv.getGioiTinh(),nv.getSDT(),
      	        			nv.getEmail(),nv.getLuong(),nv.getDiaChi()});
        	}
        	}
        });
        jButton4 = new javax.swing.JButton();
        jButton4.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	txtTNV.setText(" ");
        	txtMNV.setText(" ");
        	txtNS.setText(" ");
        	txtDiaChi.setText(" ");
        	txtSĐTNV.setText(" ");
        	txtEmailNV.setText(" ");
        	txtLuongNV.setText(" ");
        	defaultTable.setRowCount(0);
  		  ArrayList<NhanVien>list= NhanVienDAO.getInstance().selectAll();
  	        for (NhanVien nv:list) {
  	        	defaultTable.addRow(new Object[] {nv.getMaNV(),nv.getTen(),nv.getChucVu(),nv.getNgaySinh(),nv.getGioiTinh(),nv.getSDT(),
  	        			nv.getEmail(),nv.getLuong(),nv.getDiaChi()});
  	        }
  		
        	
        	
      		
        	}
        });
        jButton5 = new javax.swing.JButton();
        jButton5.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String name = JOptionPane.showInputDialog(null,"Mời bạn Nhập Tên Nhân Viên :");
        		if(name.length()>0) {
        			ArrayList<NhanVien> list=nv.getInstance().findByName(name);
        			defaultTable.setRowCount(0);
            		 
            	 for (NhanVien nv:list) {
            	  defaultTable.addRow(new Object[] {nv.getMaNV(),nv.getTen(),nv.getChucVu(),nv.getNgaySinh(),nv.getGioiTinh(),nv.getSDT(),
            	    nv.getEmail(),nv.getLuong(),nv.getDiaChi()});
            	        }
        		}
        	}
        });
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		int selectionIndex = nvTable.getSelectedRow();
                if (selectionIndex != -1) { 
                    String MaNV = (String) nvTable.getValueAt(selectionIndex, 0);
                    NhanVien nv1 = NhanVienDAO.getInstance().selectById(MaNV);

                    
                    txtMNV.setText(nv1.getMaNV());
                    txtTNV.setText(nv1.getTen());
                    txtSĐTNV.setText(nv1.getSDT());
                    ChucVuBox1.setSelectedItem(nv1.getChucVu());
                    txtEmailNV.setText(nv1.getEmail());
                    txtDiaChi.setText(nv1.getDiaChi());
                    txtNS.setText(nv1.getNgaySinh());
                    txtLuongNV.setText(nv1.getLuong() + "");
                    String gioitinh = nv1.getGioiTinh();
                    if (gioitinh.equals("Nam")) {
                        NamButton1.setSelected(true);
                    } else {
                        NuButton1.setSelected(true);
                    }
                }
        	}
        });
        nvTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Mã nhân viên:");

        jLabel3.setText("Tên Nhân Viên:");

        jLabel4.setText("Giới Tính:");

        jLabel5.setText("Chức Vụ:");

        jLabel6.setText("Ngày Sinh :");

        jLabel7.setText("Địa Chỉ:");

        jLabel8.setText("Số Điện Thoại");

        jLabel9.setText("Email:");

        jLabel10.setText("Lương:");

        NamButton1.setText("Nam");
        NamButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        NuButton1.setText("Nữ");

        ChucVuBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(BH) Bán Hàng", "(BV) Bảo Vệ", "(QL) Quản Lý", " " }));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa ");

        jButton3.setText("Xóa");

        jButton4.setText("refresh");

        jButton5.setText("Tìm Kiếm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(15)
        					.addComponent(jButton1)
        					.addGap(46)
        					.addComponent(jButton2)
        					.addPreferredGap(ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
        					.addComponent(jButton3))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(53)
        					.addComponent(jButton4)
        					.addGap(49)
        					.addComponent(jButton5)))
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(16)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton3)
        				.addComponent(jButton2))
        			.addPreferredGap(ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton4)
        				.addComponent(jButton5))
        			.addContainerGap())
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNS)
                            .addComponent(txtDiaChi)
                            .addComponent(txtSĐTNV)
                            .addComponent(txtTNV)
                            .addComponent(txtMNV)
                            .addComponent(txtEmailNV)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChucVuBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NamButton1)
                                        .addGap(26, 26, 26)
                                        .addComponent(NuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtLuongNV))
                        .addGap(79, 79, 79))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NamButton1)
                    .addComponent(NuButton1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ChucVuBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSĐTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLuongNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        nvTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Nhân Viên", "Họ Tên", "Chức vụ", "Giới Tính", "Địa Chỉ", "SĐT", "Email", "Lương"
            }
        ));
        jScrollPane1.setViewportView(nvTable);
        
        JButton btnHome = new JButton();
        btnHome.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		Home home=new Home();
        		home.setVisible(true);
        		
        	}
        });
        btnHome.setText("Home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 729, GroupLayout.PREFERRED_SIZE)
        			.addGap(0, 0, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(btnHome, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)
        			.addGap(402))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(btnHome, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(33))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	String manv=txtMNV.getText();
    	String Ten=txtTNV.getText();
    	String sdt=txtSĐTNV.getText();
    	String email=txtEmailNV.getText();
    	String diachi=txtDiaChi.getText();
    	String ngaysinh=txtNS.getText();
    	
    	nV.setMaNV(manv);
    	nV.setTen(Ten);
    	nV.setSDT(sdt);
    	nV.setChucVu(ChucVuBox1.getSelectedItem().toString());
    	nV.setEmail(email);
    	nV.setDiaChi(diachi);
    	nV.setNgaySinh(ngaysinh);
    	
    	String GioiTinh="";
    	if(NamButton1.isSelected())
    	{
    		GioiTinh="Nam";
    	}
    	else  {
    		GioiTinh="Nu";
    		
    	}
    	
    	
    	nV.setGioiTinh(GioiTinh);
    	try {
    		nV.setLuong(Integer.parseInt(txtLuongNV.getText()));
    		
    	}catch(Exception e){
    		JOptionPane.showMessageDialog(this, "Bạn phải nhập 1 số nguyên vào lương ");
    	}
    	if(manv==null||manv.isEmpty()||Ten==null||Ten.isEmpty()||sdt==null||sdt.isEmpty()||email==null||email.isEmpty()||diachi==null||diachi.isEmpty()||ngaysinh==null||ngaysinh.isEmpty()) {
    		JOptionPane.showMessageDialog(QuanLyNhanVien.this ,"Bạn chưa điền đủ thông tin ");
    		
    	}
    	else if (checkMasp(manv)==1) {
    		JOptionPane.showMessageDialog(QuanLyNhanVien.this ,"Mã sản phẩm bạn nhập đã bị trùng ");
    		
    	}
    	else  {
    		nv.getInstance().insert(nV);
    		JOptionPane.showMessageDialog(this, "Thêm thành công");
    		
    	}
    	
    	defaultTable.setRowCount(0);
		  ArrayList<NhanVien>list= NhanVienDAO.getInstance().selectAll();
	        for (NhanVien nv:list) {
	        	defaultTable.addRow(new Object[] {nv.getMaNV(),nv.getTen(),nv.getChucVu(),nv.getNgaySinh(),nv.getGioiTinh(),nv.getSDT(),
	        			nv.getEmail(),nv.getLuong(),nv.getDiaChi()});
	        }
    	
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> ChucVuBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton NamButton1;
    private javax.swing.JRadioButton NuButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable nvTable;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmailNV;
    private javax.swing.JTextField txtLuongNV;
    private javax.swing.JTextField txtMNV;
    private javax.swing.JTextField txtNS;
    private javax.swing.JTextField txtSĐTNV;
    private javax.swing.JTextField txtTNV;
    // End of variables declaration     
    private int checkMasp(String masp) {
    	for (int i=0;i<nvTable.getRowCount();i++)
    	{
    		if(masp.equals(nvTable.getValueAt(i, 0))) {
    			return 1;
    		}
    		
    	}
    	return 0;
}
}
