package view;

import java.awt.EventQueue;
import java.text.DecimalFormat;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

import DAO.HoaDonDAO;
import model.HoaDon;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JButton;

public class ThongKe extends javax.swing.JFrame {

    /**
     * Creates new form ThongKe
     */
	DefaultTableModel tkTable1;
    public ThongKe() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        DoanhThu();
        tkTable1=new DefaultTableModel() {
        	@Override
        	public boolean isCellEditable(int row, int column) {
        		// TODO Auto-generated method stub
        		return false;
        	};
        	
        };

        TKTable.setModel(tkTable1);
        tkTable1.addColumn("KhachHang");
        tkTable1.addColumn("NgayDat");
        tkTable1.addColumn("ThanhTien");
        
        
        ArrayList<HoaDon>list= HoaDonDAO.getInstance().selectAll();
        for (HoaDon hd:list) {
        	tkTable1.addRow(new Object[] {hd.getKhachHang(),hd.getNgayDat(),hd.getThanhTien()});
        }
        DoanhThu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabeltong = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNgay = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String Ngay=txtNgay.getText();
        		if(Ngay.length()>0) {
        		ArrayList<HoaDon>list=HoaDonDAO.getInstance().findByName(Ngay);
        		tkTable1.setRowCount(0);
        	        for (HoaDon hd:list) {
        	        	tkTable1.addRow(new Object[] {hd.getKhachHang(),hd.getNgayDat(),hd.getThanhTien()});
        	        }
        	        DoanhThu();
        			
        		}
        		
        	}
        });
        tkTable = new javax.swing.JScrollPane();
        TKTable = new javax.swing.JTable();
        jLabelDT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeltong.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabeltong.setText("Thống Kê Doanh Thu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tìm kiếm theo ngày");

        jButton1.setText("Tìm Kiếm");

        TKTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaHD", "NgayDat", "ThanhTien"
            }
        ));
        tkTable.setViewportView(TKTable);

        jLabelDT.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelDT.setText("Tổng Doanh Thu :");
        
        btnHome = new JButton();
        btnHome.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		Home home=new Home();
        		home.setVisible(true);
        	}
        });
        btnHome.setText("Home");
        
        JButton btnTiLi = new JButton();
        btnTiLi.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		tkTable1.setRowCount(0);
        		ArrayList<HoaDon> list=HoaDonDAO.getInstance().selectAll();
    	        for (HoaDon hd:list) {
    	        	tkTable1.addRow(new Object[] {hd.getKhachHang(),hd.getNgayDat(),hd.getThanhTien()});
    	        }
    	       
    	        DoanhThu();
    	        
        	}
        });
        btnTiLi.setText("Tải lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(98)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(txtNgay, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
        					.addGap(33)
        					.addComponent(jButton1))
        				.addComponent(jLabel2)
        				.addComponent(tkTable, GroupLayout.PREFERRED_SIZE, 495, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(108, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(61)
        			.addComponent(btnHome, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
        			.addComponent(jLabeltong, GroupLayout.PREFERRED_SIZE, 222, GroupLayout.PREFERRED_SIZE)
        			.addGap(224))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(52)
        			.addComponent(jLabelDT, GroupLayout.PREFERRED_SIZE, 388, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(261, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(505, Short.MAX_VALUE)
        			.addComponent(btnTiLi, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        			.addGap(121))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(22)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabeltong, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnHome, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
        			.addGap(26)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtNgay, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton1))
        			.addGap(32)
        			.addComponent(tkTable, GroupLayout.PREFERRED_SIZE, 364, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnTiLi)
        			.addGap(7)
        			.addComponent(jLabelDT)
        			.addContainerGap(25, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabeltong;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDT;
    private javax.swing.JScrollPane tkTable;
    private javax.swing.JTable TKTable;
    private javax.swing.JTextField txtNgay;
    private JButton btnHome;
    // End of variables declaration   
    private void DoanhThu() {
        DecimalFormat x = new DecimalFormat("###,###,###");
        int Doanhthu = 0;

        // Lặp qua từng hàng trong bảng và tính tổng doanh thu
        int tong=0;
    	for (int i=0;i<TKTable.getRowCount();i++)
    	{
    		Doanhthu+=Integer.parseInt(TKTable.getValueAt(i, 2).toString());
    	}
    	
        // Hiển thị tổng doanh thu lên label
        jLabelDT.setText("Tổng Doanh Thu: " + x.format(Doanhthu) + " VND");
    }
}
