package test;

import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.BevelBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

import DAO.CTSanPhamDAO;
import DAO.HoaDonDAO;
import DAO.SanPhamDAO;
import model.CTSanPham;
import model.HoaDon;
import model.LuuSanPham;
import model.SanPham;
import test.CapNhapDonHang;
import view.Home;
import view.TTSanPham;

public class CapNhapDonHang extends javax.swing.JFrame {

    /**
     * Creates new form CapNhapDonHang
     */
	SanPham s1;
	DefaultTableModel SpTable1;
	DefaultTableModel HDTable1;
	DefaultTableModel CTSPTable1;
    public CapNhapDonHang() {
    	
        initComponents();
        NgayDat();
       
        this.setLocationRelativeTo(null);
        SpTable1=new DefaultTableModel() {
        	@Override
        	public boolean isCellEditable(int row, int column) {
        		// TODO Auto-generated method stub
        		return false;
        	};
        };
        HDTable1=new DefaultTableModel() {
        	@Override
        	public boolean isCellEditable(int row, int column) {
        		// TODO Auto-generated method stub
        		return false;
        	};
        };
        CTSPTable1=new DefaultTableModel() {
        	@Override
        	public boolean isCellEditable(int row, int column) {
        		// TODO Auto-generated method stub
        		return false;
        	};
        };
        SpTable.setModel(SpTable1);
        SpTable1.addColumn("MaSP");
        SpTable1.addColumn("TenSP");
        SpTable1.addColumn("Loai");
        SpTable1.addColumn("Size");
        SpTable1.addColumn("Gia");
      
        
        
      
        ArrayList<SanPham>list= SanPhamDAO.getInstance().selectAll();
        for (SanPham sp:list) {
        	SpTable1.addRow(new Object[] {sp.getMaSP(),sp.getTenSp(),sp.getLoai(),sp.getSize(),sp.getGia()});
        }
        HDTable.setModel(HDTable1);
        HDTable1.addColumn("KhachHang");
        HDTable1.addColumn("NgayDat");
        HDTable1.addColumn("ThanhTien");
        ArrayList<HoaDon>list1= HoaDonDAO.getInstance().selectAll();
        for (HoaDon hd:list1)
        { HDTable1.addRow(new Object[] {hd.getKhachHang(),hd.getNgayDat(),hd.getThanhTien()});
        }
        
        CTSPTable.setModel(CTSPTable1);
        CTSPTable1.addColumn("TenSP");
        CTSPTable1.addColumn("Loai");
        CTSPTable1.addColumn("Soluong");
        CTSPTable1.addColumn("Size");
        CTSPTable1.addColumn("TongTien");
        CTSPTable1.addColumn("GhiChu");
        
        
      
        ArrayList<CTSanPham>listCT= CTSanPhamDAO.getInstance().selectAll();
        for (CTSanPham sp:listCT) {
        	CTSPTable1.addRow(new Object[] {sp.getTenSp(),sp.getLoai(),sp.getSoLuong(),sp.getSize(),sp.getTongGia(),sp.getGhiChu()});
        }
        Refresh();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDT = new javax.swing.JTextField();
        txtND = new javax.swing.JTextField();
        SanPham = new javax.swing.JScrollPane();
        SanPham.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mousePressed(MouseEvent e) {
//		     		
//
//                     
//                    
             
        	}
        });
        SpTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        CtspTable = 	new javax.swing.JScrollPane();
        CTSPTable = new javax.swing.JTable();
        CTSPTable.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
        jLabel12 = new javax.swing.JLabel();
        HoaDon = new javax.swing.JScrollPane();
        HDTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int selecIndex=SpTable.getSelectedRow();
        		if(selecIndex==-1) {
        			JOptionPane.showMessageDialog(CapNhapDonHang.this,"Vui Lòng Chọn Sản Phẩm Bạn Muốn Thêm");
        			
        		}
        		else {
        			
        			SanPham sp1=new SanPham();
        			int selectionIndex = SpTable.getSelectedRow();
                  if (selectionIndex != -1) { 
                      String MaSp = (String) SpTable.getValueAt(selectionIndex, 0);
                      SanPham sp = SanPhamDAO.getInstance().selectById(MaSp);
                      LuuSanPham.setMaSP(MaSp);
                      LuuSanPham.setGia(sp.getGia());
                   
                      
                      }
                 
             
                  
        			
        			
        			
        			
        			
        			
        		
        			
        				
        				
        			}
        		
        		
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("QUẢN LÝ ĐƠN HÀNG");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Mã Hóa Đơn");

        jLabel3.setText("Số Điện Thoai:");

        txtHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKHActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên Khách Hàng");

        jLabel5.setText("Ngày Đặt:");
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		CTSPTable1.setRowCount(0);
        		String maHoaDon = "HD"  + (int)(Math.random()*1000);
        		txtHD.setText(maHoaDon);
        		
       		 
      		
        	}
        });
        
                jButton1.setText("Tạo Hóa Đơn");
        jButton4 = new javax.swing.JButton();
        
                jButton4.setText("Thanh Toán");
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton4ActionPerformed(evt);
                    }
                });
        
        JLabel lblThnhTin = new JLabel();
        lblThnhTin.setText("Thành Tiền");
        
        txtTien = new JTextField();
        
        JLabel lblTinKhchTr = new JLabel();
        lblTinKhchTr.setText("Tiền khách trả");
        
        JLabel lblTinD = new JLabel();
        lblTinD.setText("Tiền Dư");
        
        textField_1 = new JTextField();
        
        textField_2 = new JTextField();
        
        txtKH = new JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jButton1)
        					.addGap(24))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        								.addComponent(txtTien, Alignment.LEADING)
        								.addComponent(txtDT, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtHD, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE))
        							.addGap(64))
        						.addComponent(lblThnhTin, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel2)
        							.addPreferredGap(ComponentPlacement.RELATED, 107, Short.MAX_VALUE)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblTinD, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel5)
        						.addComponent(lblTinKhchTr, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel4))
        					.addGap(30)))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jButton4)
        				.addComponent(textField_1, GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(textField_2, GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
        				.addComponent(txtKH, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtND))
        			.addGap(14))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(35)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(txtHD, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4)
        				.addComponent(txtKH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(27)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(txtDT, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtND, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5))
        			.addGap(33)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblThnhTin)
        				.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtTien, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblTinKhchTr))
        			.addGap(34)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblTinD)
        				.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton4))
        			.addGap(24))
        );
        jPanel1.setLayout(jPanel1Layout);

        SpTable.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null, null},
        	},
        	new String[] {
        		"MaSanPham", "TenSP ", "Loai", "Size", "Gia"
        	}
        ));
        SpTable.getColumnModel().getColumn(1).setPreferredWidth(153);
        SanPham.setViewportView(SpTable);

        jLabel11.setText("Chi Tiết Hóa Đơn");

        CTSPTable.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"TenSP ", "Loai", "SoLuong", "Size", "TongTien", "GhiChu"
        	}
        ));
        CtspTable.setViewportView(CTSPTable);

        jLabel12.setText("Tìm kiếm sản phẩm");

        HDTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KhachHang", "NgayDat", "ThanhTien"
            }
        ));
        HoaDon.setViewportView(HDTable);

        jLabel16.setText("Bảng hóa đơn");

        jButton2.setText("Thêm Sản Phẩm");
        
        JButton deleteSP = new JButton();
        deleteSP.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int deleteIndex=CTSPTable.getSelectedRow();
        		if(deleteIndex==-1) {
        			JOptionPane.showMessageDialog(CapNhapDonHang.this,"Vui lòng chọn sản phẩm ","Lỗi",JOptionPane.ERROR_MESSAGE);
        			
        		}
        		else {
        			int confirm = JOptionPane.showConfirmDialog(CapNhapDonHang.this, "Bạn có chắc chắc muốn xóa không ?");
        			if(confirm==JOptionPane.YES_OPTION) {
        				String MaSp=(String)CTSPTable.getValueAt(deleteIndex, 0);
        				CTSanPhamDAO.getInstance().delete(MaSp);
        				
        			}
        		}
        		Refresh();
        	}
        	
        });
        deleteSP.setText("Xóa Sản Phẩm");
        
        btnHome = new JButton();
        btnHome.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        		Home home=new Home();
        		home.setVisible(true);
        	}
        });
        btnHome.setText("Home");
        
        textFind = new JTextField();
        
        JButton btnTmKim = new JButton();
        btnTmKim.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String sanpham=textFind.getText();
        		if(sanpham!=null) {
        			ArrayList<model.SanPham> list=SanPhamDAO.getInstance().findByName(sanpham);
        			SpTable1.setRowCount(0);
        			 for (SanPham sp:list) {
        		        	SpTable1.addRow(new Object[] {sp.getMaSP(),sp.getTenSp(),sp.getLoai(),sp.getSize(),sp.getGia()});
        		        }
        		       
        			
        		}
        		else {
        			JOptionPane.showMessageDialog(CapNhapDonHang.this,"Vui lòng nhâp sản phầm bạn muốn tìm ");
        			
        		}
        		
        	}
        });
        btnTmKim.setText("Tìm Kiếm");
        
        JLabel jLabel12_1 = new JLabel();
        jLabel12_1.setText("Bảng Sản Phẩm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btnHome)
        					.addGap(234)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 214, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(5)
        							.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(textFind, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(btnTmKim, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE))
        						.addComponent(jLabel12)
        						.addComponent(jLabel12_1, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jButton2)
        							.addGap(35)
        							.addComponent(deleteSP, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE))
        						.addComponent(CtspTable, GroupLayout.PREFERRED_SIZE, 421, GroupLayout.PREFERRED_SIZE)
        						.addComponent(SanPham, GroupLayout.PREFERRED_SIZE, 438, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
        						.addComponent(HoaDon)
        						.addComponent(jPanel1, 0, 0, Short.MAX_VALUE))))
        			.addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jLabel1))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(btnHome, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 282, GroupLayout.PREFERRED_SIZE)
        					.addGap(34)
        					.addComponent(jLabel16))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel12)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(textFind, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnTmKim))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jLabel12_1)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(SanPham, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jButton2)
        						.addComponent(deleteSP))))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(HoaDon, GroupLayout.PREFERRED_SIZE, 290, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jLabel11)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(CtspTable, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)))
        			.addGap(157))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void txtKHActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
//    	String nd = txtND.getText();
//    	String ten = txtHD.getText();
//    	String DiaChi = txtDC.getText();
//    	String Sdt = txtDT.getText();
//    	if (nd != null && !nd.isEmpty() && ten != null && !ten.isEmpty() && DiaChi != null && !DiaChi.isEmpty() && Sdt != null && !Sdt.isEmpty()) {
//    		int tong=0;
//        	for (int i=0;i<CTSPTable.getRowCount();i++)
//        	{
//        		tong+=Integer.parseInt(CTSPTable.getValueAt(i, 2).toString());
//        	}
//        	System.out.println(nd+""+ten+""+tong);
//        	HoaDon hd=new HoaDon(ten,nd,tong);
//        	HoaDonDAO.getInstance().insert(hd);
//        	HDTable1.setRowCount(0);
//        	 ArrayList<HoaDon>list1= HoaDonDAO.getInstance().selectAll();
//             for (HoaDon hD:list1)
//             { HDTable1.addRow(new Object[] {hD.getKhachHang(),hD.getNgayDat(),hD.getThanhTien()});
//             }
//    	} else {
//    	    JOptionPane.showMessageDialog(CapNhapDonHang.this, "Vui lòng điền đầy đủ thông tin");
//    	}
    	
    	
    	
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhapDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhapDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhapDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhapDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapNhapDonHang().setVisible(true);
            }
        });
    }
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane SanPham;
    private javax.swing.JScrollPane CtspTable;
    private javax.swing.JScrollPane HoaDon;
    private javax.swing.JTable SpTable;
    private javax.swing.JTable CTSPTable;
    private javax.swing.JTable HDTable;
    private javax.swing.JTextField txtDT;
    private javax.swing.JTextField txtHD;
    private javax.swing.JTextField txtND;
    private JButton btnHome;
    private JTextField txtTien;
    private JTextField textField_1;
    private JTextField textField_2;
    private JTextField textFind;
    private JTextField txtKH;
    private void NgayDat() {
    	Date date = new Date();
    	// Định dạng ngày tháng
    	SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    	String ngayDat = sdf.format(date);
    	txtND.setText(ngayDat);
    }
    private void Refresh() {
    	CTSPTable1.setRowCount(0);
		 ArrayList<CTSanPham>listCT= CTSanPhamDAO.getInstance().selectAll();
	        for (CTSanPham sp:listCT) {
	        	CTSPTable1.addRow(new Object[] {sp.getTenSp(),sp.getLoai(),sp.getSoLuong(),sp.getSize(),sp.getTongGia(),sp.getGhiChu()});
	        }
    }
    private void MaHoaDon() {
    	
    }
}
